### PR TITLE
Russian Translation for TAC LS

### PR DESCRIPTION
**Pull request by Tirathangil**
OK, I did it. Of course, translation is not literal, word by word, but I hope that it is adequate enough. Fixed some bags, translated all items. Full in-game translation also require translation of "Community Resource Pack".

### CODE REVIEW

**Comment by JPLRepo** [comment]
Wrong branch. But thank you very much.
I will pick the change to the cfg file for Russian only as the other changes have already been made to that branch.

**Comment by Tirathangil** [comment]
OK, no problem. In any case, it was a pleasure for me to work on the translation. :)

**Comment by JPLRepo** [comment]
Don't get me wrong. Thanks very much and I have copied the Russian translations into develop branch and will add your name as the author of the translation.
Thanks Again!

**Comment by Tirathangil** [comment]
> Don't get me wrong. Thanks very much and I have copied the Russian translations into develop branch and will add your name as the author of the translation.
Thanks Again!

I understood. In short, I liked working on translations. If there are any more modifications that need to be translated - I'm always ready to help.
Thank you very much for the interesting mod. :)

**Pull request closed without merging**
