### PR TITLE
Don't handle resources if RealismOverhaul is installed

### PR DESCRIPTION
**Pull request by ghost**
There is no need to add Resources, RealismOverhaul handle it

### CODE REVIEW

**Comment by NathanKell** [comment]
Actually RO does rely on TACLS doing this...

**Comment by ghost** [comment]
Why and where?

Squad Modules have full support without doing this.

Do you think this is necessary for people using mods with no RO support or is there work to do in supported mods?

**Comment by JPLRepo** [comment]
Need update clarity here. Why are you wanting to remove Life Support resources if RO is installed?
NathanKell has said RO relies on this. So this PR should be closed and not merged?

**Comment by JPLRepo** [comment]
@NathanKell can you confirm RO does need TACLS to do this? Will close PR if that is the case. Thanks.

**Comment by NathanKell** [comment]
@EagleEyeLogic is making RO side changes at present, as I understand it, so (assuming I am correct about what that means) it should be closed for now, yes.

**Comment by JPLRepo** [comment]
@EagleEyeLogic  According to @NathanKell  - these changes should not be made to TAC LS but made on the RO side. Please confirm what you are changing?

**Pull request closed without merging**
